Repository pknu-wap/WABI-BE, pull requests merged in 2024-09, with the labels that each got.

#2 Feat/#1 - p1 기능
  wabi/.gitignore
  wabi/build.gradle.kts
  wabi/src/main/kotlin/com/wap/wabi/band/controller/BandController.kt
  wabi/src/main/kotlin/com/wap/wabi/band/controller/BandEnrollController.kt
  wabi/src/main/kotlin/com/wap/wabi/band/entity/Band.java
  wabi/src/main/kotlin/com/wap/wabi/band/entity/BandStudent.java
  wabi/src/main/kotlin/com/wap/wabi/band/payload/BandStudentDto.kt
  wabi/src/main/kotlin/com/wap/wabi/band/payload/request/EnrollRequest.kt
  wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandStudentData.kt
  wabi/src/main/kotlin/com/wap/wabi/band/repository/BandRepository.java
  wabi/src/main/kotlin/com/wap/wabi/band/repository/BandStudentRepository.java
  wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
  wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
  wabi/src/main/kotlin/com/wap/wabi/band/service/FileToBandStudentTranslator.kt
  wabi/src/main/kotlin/com/wap/wabi/common/payload/response/Response.kt
  wabi/src/main/kotlin/com/wap/wabi/event/controller/EventController.kt
  wabi/src/main/kotlin/com/wap/wabi/event/entity/Enum/EventStudentStatus.java
  wabi/src/main/kotlin/com/wap/wabi/event/entity/Event.java
  wabi/src/main/kotlin/com/wap/wabi/event/entity/EventBand.java
  wabi/src/main/kotlin/com/wap/wabi/event/entity/EventStudent.java
  wabi/src/main/kotlin/com/wap/wabi/event/payload/request/CheckInRequest.kt
  wabi/src/main/kotlin/com/wap/wabi/event/payload/response/CheckInStatusCount.kt
  wabi/src/main/kotlin/com/wap/wabi/event/payload/response/Enum/CheckInTableFilter.kt
  wabi/src/main/kotlin/com/wap/wabi/event/payload/response/EventStudentData.kt
  wabi/src/main/kotlin/com/wap/wabi/event/repository/EventBandRepository.java
  wabi/src/main/kotlin/com/wap/wabi/event/repository/EventRepository.java
  wabi/src/main/kotlin/com/wap/wabi/event/repository/EventStudentRepository.java
  wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
  wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
  wabi/src/main/kotlin/com/wap/wabi/exception/GlobalExceptionHandler.kt
  wabi/src/main/kotlin/com/wap/wabi/exception/RestApiException.kt
  wabi/src/main/kotlin/com/wap/wabi/student/entity/Student.java
  wabi/src/main/kotlin/com/wap/wabi/student/repository/StudentRepository.java
  wabi/src/main/resources/application-local.properties
  wabi/src/main/resources/application-prod.properties
  wabi/src/main/resources/application.properties
Labels: Feat, 제페론, 양갱, 듀

#8 [Test][Feature] 이벤트 테스트 코드 & 기능 구현 (#4)
  wabi/.gitignore
  wabi/Dockerfile
  wabi/src/main/kotlin/com/wap/wabi/WabiApplication.kt
  wabi/src/main/kotlin/com/wap/wabi/band/controller/BandController.kt
  wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandShortData.kt
  wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandStudentsData.kt
  wabi/src/main/kotlin/com/wap/wabi/band/repository/BandRepository.java
  wabi/src/main/kotlin/com/wap/wabi/common/config/WebConfig.kt
  wabi/src/main/kotlin/com/wap/wabi/common/payload/response/Response.kt
  wabi/src/main/kotlin/com/wap/wabi/event/controller/EventController.kt
  wabi/src/main/kotlin/com/wap/wabi/event/entity/Event.java
  wabi/src/main/kotlin/com/wap/wabi/event/entity/EventStudent.java
  wabi/src/main/kotlin/com/wap/wabi/event/payload/request/EventCreateRequest.kt
  wabi/src/main/kotlin/com/wap/wabi/event/payload/request/EventUpdateRequest.kt
  wabi/src/main/kotlin/com/wap/wabi/event/payload/response/EventData.kt
  wabi/src/main/kotlin/com/wap/wabi/event/payload/response/EventStudentData.kt
  wabi/src/main/kotlin/com/wap/wabi/event/repository/EventBandRepository.java
  wabi/src/main/kotlin/com/wap/wabi/event/repository/EventRepository.java
  wabi/src/main/kotlin/com/wap/wabi/event/repository/EventStudentRepository.java
  wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
  wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
  wabi/src/main/kotlin/com/wap/wabi/exception/GlobalExceptionHandler.kt
  wabi/src/main/resources/application-local.properties
  wabi/src/main/resources/application-prod.properties
  wabi/src/test/kotlin/com/wap/wabi/band/fixture/BandFixture.kt
  wabi/src/test/kotlin/com/wap/wabi/band/fixture/BandStudentFixture.kt
  wabi/src/test/kotlin/com/wap/wabi/band/service/BandServiceTest.kt
  wabi/src/test/kotlin/com/wap/wabi/common/Reflection.kt
  wabi/src/test/kotlin/com/wap/wabi/common/TestConstants.kt
  wabi/src/test/kotlin/com/wap/wabi/event/fixture/EventBandFixture.kt
  wabi/src/test/kotlin/com/wap/wabi/event/fixture/EventFixture.kt
  wabi/src/test/kotlin/com/wap/wabi/event/fixture/EventStudentFixture.kt
  wabi/src/test/kotlin/com/wap/wabi/event/service/EventServiceTest.kt
  wabi/src/test/kotlin/com/wap/wabi/student/fixture/StudentFixture.kt
Labels: Feat, 듀

#7 Feat/#5 그룹 관련 기능
  wabi/src/main/kotlin/com/wap/wabi/band/controller/BandController.kt
  wabi/src/main/kotlin/com/wap/wabi/band/entity/Band.java
  wabi/src/main/kotlin/com/wap/wabi/band/payload/request/BandCreateRequest.kt
  wabi/src/main/kotlin/com/wap/wabi/band/payload/request/BandUpdateRequest.kt
  wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandsData.kt
  wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
  wabi/src/test/kotlin/com/wap/wabi/band/service/BandEnrollServiceTest.kt
  wabi/src/test/kotlin/com/wap/wabi/band/service/BandServiceTest.kt
  wabi/src/test/kotlin/com/wap/wabi/student/fixture/StudentFixture.kt
Labels: Feat, 양갱

#12 [Fix] bandNames 문자열 생성 로직 수정(#10)
  wabi/src/main/kotlin/com/wap/wabi/event/payload/response/EventStudentData.kt
  wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
Labels: Fix

#13 Feat/#10
  wabi/src/main/kotlin/com/wap/wabi/band/entity/Band.java
  wabi/src/main/kotlin/com/wap/wabi/band/payload/request/BandUpdateRequest.kt
  wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
Labels: Feat, Fix, 듀

#14 [Chore] Swagger 설명 추가
  wabi/src/main/kotlin/com/wap/wabi/band/controller/BandController.kt
  wabi/src/main/kotlin/com/wap/wabi/band/controller/BandEnrollController.kt
Labels: Chore, 듀

#16 feat: SwaggerConfig 추가
  wabi/src/main/kotlin/com/wap/wabi/common/config/SwaggerConfig.kt
Labels: Feat, 양갱

#18 Fix: check -> if 수정
  wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
Labels: Fix, 양갱

#19 fix: 빠진 throw 추가
  wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
Labels: Fix, 양갱

#20 [Fix] : 엑셀 데이터가 비어있으면 빈문자열로 db에 저장한다.
  wabi/src/main/kotlin/com/wap/wabi/band/service/FileToBandStudentTranslator.kt
  wabi/src/main/resources/application.properties
Labels: Fix

#21 [Fix] 시간대를 한국으로 설정하기 위한 변경
  wabi/src/main/kotlin/com/wap/wabi/WabiApplication.kt
Labels: Fix
