Repository pknu-wap/WABI-BE, pull requests merged in 2024-12, with the labels that each got.

#42 [Feature] HealthCheckController 접근 허용 및 EOL 추가
  wabi/src/main/kotlin/com/wap/wabi/auth/config/SecurityConfig.kt
  wabi/src/main/kotlin/com/wap/wabi/common/HealthCheckController.kt
Labels: Feat, Refactor, 듀

#55 Deploy/#52 - Refresh 토큰으로 인한 Github Repo Secret & 서버 .env 파일 수정
  .github/workflows/gradle.yml
  wabi/src/main/resources/application-prod.properties
Labels: Deploy

#57 [Feature] 모니터링 구현
  wabi/build.gradle.kts
  wabi/src/main/kotlin/com/wap/wabi/WabiApplication.kt
  wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Admin.java
  wabi/src/main/kotlin/com/wap/wabi/auth/admin/service/AdminService.kt
  wabi/src/main/kotlin/com/wap/wabi/auth/admin/util/UserActivityManager.kt
  wabi/src/main/kotlin/com/wap/wabi/auth/config/SecurityConfig.kt
  wabi/src/main/kotlin/com/wap/wabi/auth/jwt/JwtAuthenticationFilter.kt
  wabi/src/main/kotlin/com/wap/wabi/common/RequestLoggingInterceptor.kt
  wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
  wabi/src/main/resources/application.properties
Labels: Feat, 듀, Deploy

#60 fix: github actions docker build 파일 경로 문제 수정
  .github/workflows/build.yml
Labels: Fix, 제페론
